### ISSUE TITLE
Lags

### ISSUE THREAD

**Issue by petrovivanvlad** [sriharshachilakapati/Blox#1]
Just downloaded and compiled the game with Eclipse IDE, but on second level I've got lags - around 6 FPS.
Second level always restarts. How to play third level? Or it's not the same version as you showed us on youtube link below?

**Comment by sriharshachilakapati** [comment]
Yes that is a problem, and it was caused by the scene graph. There is some issue with the forward rendering system and the scenes. I will possibly think of this again once I re-implemented the scene graph in SilenceEngine.

Right now, I only have two levels, so it restarts. My more important priorities are first document the existing API of SilenceEngine, and to make a alpha release. Thanks for trying it though.

**Comment by sriharshachilakapati** [comment]
I have successfully fixed the issue of lags. It runs at solid 60 FPS now. Will add more levels soon.
